5-shinsekai/shinsekai-BE

build.gradle, src/main/java/com/example/shinsekai/card/application/StarbucksCardKeyMapService.java, src/main/java/com/example/shinsekai/card/application/StarbucksCardKeyMapServiceImpl.java, src/main/java/com/example/shinsekai/card/application/StarbucksCardService.java, src/main/java/com/example/shinsekai/card/application/StarbucksCardServiceImpl.java, src/main/java/com/example/shinsekai/card/dto/in/StarbucksCardKeyMapRequestDto.java, src/main/java/com/example/shinsekai/card/dto/in/StarbucksCardRequestDto.java, src/main/java/com/example/shinsekai/card/dto/out/StarbucksCardResponseDto.java, src/main/java/com/example/shinsekai/card/entity/StarbucksCard.java, src/main/java/com/example/shinsekai/card/entity/StarbucksCardKeyMap.java, src/main/java/com/example/shinsekai/card/infrastructure/StarbucksCardKeyMapRepository.java, src/main/java/com/example/shinsekai/card/infrastructure/StarbucksCardRepository.java, src/main/java/com/example/shinsekai/card/presentation/controller/StarbucksCardController.java, src/main/java/com/example/shinsekai/card/presentation/controller/StarbucksCardKeyMapController.java, src/main/java/com/example/shinsekai/card/vo/StarbucksCardKeyMapRequestVo.java, src/main/java/com/example/shinsekai/card/vo/StarbucksCardRequestVo.java, src/main/java/com/example/shinsekai/card/vo/StarbucksCardResponseVo.java, src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java, src/main/java/com/example/shinsekai/order/entity/Order.java, src/main/java/com/example/shinsekai/order/entity/OrderProductList.java, src/main/java/com/example/shinsekai/order/entity/OrderStatus.java, src/main/java/com/example/shinsekai/payment/entity/Payment.java
- Closes #7 
- 관리자 > 스타벅스 카드 생성(카드 번호 + 핀번호 )
- 스타벅스 카드 등록
- 등록한 스타벅스 카드 리스트 조회
- 
=> Feat/스타벅스 카드 등록, 조회API

src/main/java/com/example/shinsekai/season/entity/ProductSeasonList.java, src/main/java/com/example/shinsekai/season/entity/Season.java
- Closes #28 
- Season Entity 생성
- ProductSeasonList Entity 생성
=> Feat: Season entity 생성

src/main/java/com/example/shinsekai/event/entity/Event.java, src/main/java/com/example/shinsekai/event/entity/ProductEventList.java
- Closes #30   
- Event Entity 생성
- ProductEventList Entity 생성
=> Feat: Event entity 생성

build.gradle, src/main/java/com/example/shinsekai/common/config/S3Config.java, src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java, src/main/java/com/example/shinsekai/common/service/S3Service.java, src/main/java/com/example/shinsekai/product/application/ProductService.java, src/main/java/com/example/shinsekai/product/application/ProductServiceImpl.java, src/main/java/com/example/shinsekai/product/dto/in/ProductRequestDto.java, src/main/java/com/example/shinsekai/product/entity/Product.java, src/main/java/com/example/shinsekai/product/entity/ProductStatus.java, src/main/java/com/example/shinsekai/product/entity/option/ProductOptionList.java, src/main/java/com/example/shinsekai/product/infrastructure/ProductRepository.java, src/main/java/com/example/shinsekai/product/presentation/ProductController.java
=> 상품관련 API #5

src/main/java/com/example/shinsekai/address/application/AddressServiceImpl.java, src/main/java/com/example/shinsekai/address/dto/in/AddressRequestDto.java, src/main/java/com/example/shinsekai/address/entity/Address.java, src/main/java/com/example/shinsekai/address/infrastructure/AddressCustomRepoImpl.java, src/main/java/com/example/shinsekai/address/infrastructure/AddressCustomRepository.java, src/main/java/com/example/shinsekai/address/presentation/AddressController.java, src/main/java/com/example/shinsekai/address/vo/AddressCreateRequestVo.java, src/main/java/com/example/shinsekai/address/vo/AddressUpdateRequestVo.java
- #57 
- Address엔티티에서 memberUuid unique 속성 제거
- AddressCustomRepository 내에 메서드 이름 명시
=> Feat: 배송지 api개발(5)

src/main/java/com/example/shinsekai/category/application/ProductCategoryListService.java, src/main/java/com/example/shinsekai/category/application/ProductCategoryListServiceImpl.java, src/main/java/com/example/shinsekai/category/dto/in/ProductCategoryListCreateRequestDto.java, src/main/java/com/example/shinsekai/category/dto/in/ProductCategoryListDeleteRequestDto.java, src/main/java/com/example/shinsekai/category/dto/in/ProductCategoryListGetByProductCodeRequestDto.java, src/main/java/com/example/shinsekai/category/dto/in/ProductCategoryListGetRequestDto.java, src/main/java/com/example/shinsekai/category/dto/in/ProductCategoryListUpdateRequestDto.java, src/main/java/com/example/shinsekai/category/dto/out/ProductCategoryListGetResponseDto.java, src/main/java/com/example/shinsekai/category/entity/ProductCategoryList.java, src/main/java/com/example/shinsekai/category/infrastructure/ProductCategoryListRepository.java, src/main/java/com/example/shinsekai/category/presentation/ProductCategoryListController.java, src/main/java/com/example/shinsekai/category/vo/in/ProductCategoryListCreateRequestVo.java, src/main/java/com/example/shinsekai/category/vo/in/ProductCategoryListUpdateRequestVo.java, src/main/java/com/example/shinsekai/category/vo/out/ProductCategoryListGetResponseVo.java, src/main/java/com/example/shinsekai/common/config/SecurityConfig.java, src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java
- Resolves: #67
- ProductCategoryList 생성
- ProductCategoryList 조회(by id, productCode)
- ProductCategoryList 삭제(하나, 여러개)
- ProductCategoryList 수정
- SecurityConfig product-category 허용 추가
=> Feat: ProductCategoryList 관련 API

src/main/java/com/example/shinsekai/external/starbucksCard/application/ExternalStarbucksCardService.java, src/main/java/com/example/shinsekai/external/starbucksCard/dto/ExternalStarbucksCardResponseDto.java, src/main/java/com/example/shinsekai/external/starbucksCard/vo/ExternalStarbucksCardRequestVo.java, src/main/java/com/example/shinsekai/external/starbucksCard/vo/ExternalStarbucksCardResponseVo.java
- Closed #64 
-  요청, 응답 카드 이름 추가
=> Fix: 스타벅스 카드 랜덤생성 수정

src/main/java/com/example/shinsekai/product/application/ProductSearchService.java, src/main/java/com/example/shinsekai/product/application/ProductSearchServiceImpl.java, src/main/java/com/example/shinsekai/product/infrastructure/ProductSearchRepositoryCustom.java, src/main/java/com/example/shinsekai/product/infrastructure/ProductSearchRepositoryImpl.java, src/main/java/com/example/shinsekai/product/presentation/ProductController.java
Resolves : #81
- 상품명을 키워드로 검색하여 해당 상품들의 productCode만 반환하는 검색 API 구현
- QueryDSL을 통해 `product.productName.containsIgnoreCase(keyword)` 조건으로 부분 문자열 검색 처리
- 페이징 처리된 `Page<String>` 응답 구조 적용
- 컨트롤러 경로: `GET /api/v1/product/search`
=> Feat: 상품명 기반 productCode 검색 API 추가

src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java, src/main/java/com/example/shinsekai/season/application/SeasonService.java, src/main/java/com/example/shinsekai/season/application/SeasonServiceImpl.java, src/main/java/com/example/shinsekai/season/dto/in/SeasonCreateRequestDto.java, src/main/java/com/example/shinsekai/season/dto/in/SeasonUpdateRequestDto.java, src/main/java/com/example/shinsekai/season/dto/out/SeasonGetResponseDto.java, src/main/java/com/example/shinsekai/season/infrastructure/ProductSeasonListRepository.java, src/main/java/com/example/shinsekai/season/presentation/SeasonController.java, src/main/java/com/example/shinsekai/season/vo/in/SeasonCreateRequestVo.java, src/main/java/com/example/shinsekai/season/vo/in/SeasonUpdateRequestVo.java, src/main/java/com/example/shinsekai/season/vo/out/SeasonGetResponseVo.java
- Resolves: #84
- Season 생성
- Season 조회(단일, 전체)
- Season 수정
- Season 삭제
=> Feat: Season 관련 API

src/main/java/com/example/shinsekai/event/entity/Event.java, src/main/java/com/example/shinsekai/event/entity/ProductEventList.java
- Resolves: #30
- text field 선언
- productId -> productCode 변경
=> Fix: Event, ProductEventList Entity 수정

src/main/java/com/example/shinsekai/common/config/SecurityConfig.java, src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java, src/main/java/com/example/shinsekai/event/application/EventService.java, src/main/java/com/example/shinsekai/event/application/EventServiceImpl.java, src/main/java/com/example/shinsekai/event/dto/in/EventCreateRequestDto.java, src/main/java/com/example/shinsekai/event/dto/in/EventUpdateRequestDto.java, src/main/java/com/example/shinsekai/event/dto/out/EventGetDetailResponseDto.java, src/main/java/com/example/shinsekai/event/dto/out/EventGetTitleResponseDto.java, src/main/java/com/example/shinsekai/event/entity/Event.java, src/main/java/com/example/shinsekai/event/infrastructure/EventRepository.java, src/main/java/com/example/shinsekai/event/infrastructure/ProductEventListRepository.java, src/main/java/com/example/shinsekai/event/presentation/EventController.java, src/main/java/com/example/shinsekai/event/vo/in/EventCreateRequestVo.java, src/main/java/com/example/shinsekai/event/vo/in/EventUpdateRequestVo.java, src/main/java/com/example/shinsekai/event/vo/out/EventGetDetailResponseVo.java, src/main/java/com/example/shinsekai/event/vo/out/EventGetTitleResponseVo.java
- Resolves #88
- 이벤트 생성
- 이벤트 조회
- 이벤트 수정
- 이벤트 삭제
- 이벤트 entity 수정
=> Feat: event 관련 API

src/main/java/com/example/shinsekai/card/dto/in/StarbucksCardRequestDto.java, src/main/java/com/example/shinsekai/card/dto/out/StarbucksCardResponseDto.java, src/main/java/com/example/shinsekai/card/entity/StarbucksCard.java, src/main/java/com/example/shinsekai/card/presentation/StarbucksCardController.java, src/main/java/com/example/shinsekai/card/vo/in/StarbucksCardRequestVo.java, src/main/java/com/example/shinsekai/card/vo/out/StarbucksCardResponseVo.java
- Resolves #55
- 액세스 토큰 추가
- 코드 컨벤션
- 에러 처리
- 이용동의 추가
=> Feat: 스타벅스 카드 API 수정

src/main/java/com/example/shinsekai/payment/application/PaymentService.java, src/main/java/com/example/shinsekai/payment/application/PaymentServiceImpl.java, src/main/java/com/example/shinsekai/payment/dto/in/PaymentDeleteRequestDto.java, src/main/java/com/example/shinsekai/payment/dto/in/PaymentRequestDto.java, src/main/java/com/example/shinsekai/payment/entity/Payment.java, src/main/java/com/example/shinsekai/payment/entity/PaymentStatus.java, src/main/java/com/example/shinsekai/payment/infrastructure/PaymentRepository.java, src/main/java/com/example/shinsekai/payment/presentation/PaymentController.java, src/main/java/com/example/shinsekai/purchase/application/OrderService.java, src/main/java/com/example/shinsekai/purchase/application/OrderServiceImpl.java, src/main/java/com/example/shinsekai/purchase/application/PurchaseService.java, src/main/java/com/example/shinsekai/purchase/application/PurchaseServiceImpl.java, src/main/java/com/example/shinsekai/purchase/dto/in/CancelOrderRequestDto.java, src/main/java/com/example/shinsekai/purchase/dto/in/OrderRequestDto.java, src/main/java/com/example/shinsekai/purchase/dto/in/PurchaseDeleteRequestDto.java, src/main/java/com/example/shinsekai/purchase/dto/in/PurchaseProductListRequestDto.java, src/main/java/com/example/shinsekai/purchase/dto/in/PurchaseRequestDto.java, src/main/java/com/example/shinsekai/purchase/dto/in/PurchaseTemporaryRequestDto.java, src/main/java/com/example/shinsekai/purchase/entity/Purchase.java, src/main/java/com/example/shinsekai/purchase/entity/PurchaseProductList.java, src/main/java/com/example/shinsekai/purchase/entity/PurchaseStatus.java, src/main/java/com/example/shinsekai/purchase/infrastructure/PurchaseProductListRepository.java, src/main/java/com/example/shinsekai/purchase/infrastructure/PurchaseRepository.java, src/main/java/com/example/shinsekai/purchase/presentation/PurchaseController.java, src/main/java/com/example/shinsekai/purchase/vo/in/CancelOrderRequestVo.java, src/main/java/com/example/shinsekai/purchase/vo/in/OrderRequestVo.java, src/main/java/com/example/shinsekai/purchase/vo/in/PurchaseProductRequestVo.java
- Resolves:#90
- 간편결제 제거
- 결제, 주문, 스타벅스 카드 결제, (재고) 한 트랜잭션으로 통합 (Order)
- Enum 변경(purchaseStatus, paymentStatus)
- orderVo, dto 에서 paymentstatus 변수 명 변경(주문 정보와 함께 받아와서 status 두가지라 혼동 방지를 위해)
- 주문 코드 생성 위치 변경(orderDto) 및 주문 상품 vo,dto 에서 주문 코드 중복 제거
=> Fix : 주문 API

src/main/java/com/example/shinsekai/address/application/AddressServiceImpl.java, src/main/java/com/example/shinsekai/address/dto/in/AddressCreateRequestDto.java, src/main/java/com/example/shinsekai/address/dto/in/AddressUpdateRequestDto.java, src/main/java/com/example/shinsekai/address/dto/out/AddressResponseDto.java, src/main/java/com/example/shinsekai/address/entity/Address.java, src/main/java/com/example/shinsekai/address/infrastructure/AddressRepository.java, src/main/java/com/example/shinsekai/address/presentation/AddressController.java, src/main/java/com/example/shinsekai/address/vo/AddressCreateRequestVo.java, src/main/java/com/example/shinsekai/address/vo/AddressResponseVo.java, src/main/java/com/example/shinsekai/address/vo/AddressUpdateRequestVo.java, src/main/java/com/example/shinsekai/common/config/SecurityConfig.java, src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java
- Resolved #100 
- 배송지 컬럼 분리(도로명, 상세주소)
- 메인 주소지여부 컬럼 추가
- 메소드 간소화
=> Fix: 배송지API 리팩토링

src/main/java/com/example/shinsekai/card/application/StarbucksCardService.java, src/main/java/com/example/shinsekai/card/application/StarbucksCardServiceImpl.java, src/main/java/com/example/shinsekai/card/entity/StarbucksCard.java, src/main/java/com/example/shinsekai/card/infrastructure/MemberStarbucksListRepository.java, src/main/java/com/example/shinsekai/card/presentation/StarbucksCardController.java, src/main/java/com/example/shinsekai/card/vo/in/ChargeStarbucksCardVo.java
- Resolves #103 
- 스타벅스 카드 충전 API 추가
=> Feat : 스타벅스 카드 충전 API

src/main/java/com/example/shinsekai/event/entity/Event.java, src/main/java/com/example/shinsekai/event/entity/ProductEventList.java
- Resolves: #88
- Event, ProductEventList에 추가
=> Feat: event

src/main/java/com/example/shinsekai/season/entity/ProductSeasonList.java
- Resolves: #28
- ProductSeasonList에 추가
=> Feat: ProductSeason BaseEntity 추가

src/main/java/com/example/shinsekai/product/application/ProductJsonUploadService.java
=> Feat: Json 파일 상품 업로드 API

src/main/java/com/example/shinsekai/cart/application/CartService.java, src/main/java/com/example/shinsekai/cart/application/CartServiceImpl.java, src/main/java/com/example/shinsekai/cart/dto/in/CartCheckedUpdateRequestDto.java, src/main/java/com/example/shinsekai/cart/entity/CartItemType.java, src/main/java/com/example/shinsekai/cart/infrastructure/CartRepository.java, src/main/java/com/example/shinsekai/cart/presentation/CartController.java, src/main/java/com/example/shinsekai/cart/vo/in/CartCheckedUpdateRequestVo.java
- Resolves #9 
- Resolves #21
- CartChecked 전체 상태 변경 구현
- mebmerUuid 조회 코드 refactoring
=> Feat: Cart

src/main/java/com/example/shinsekai/ShinsekaiApplication.java, src/main/java/com/example/shinsekai/common/config/SecurityConfig.java, src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java, src/main/java/com/example/shinsekai/common/jwt/JwtTokenProvider.java, src/main/java/com/example/shinsekai/member/application/KakaoAuthService.java, src/main/java/com/example/shinsekai/member/application/KakaoAuthServiceImpl.java, src/main/java/com/example/shinsekai/member/application/MemberServiceImpl.java, src/main/java/com/example/shinsekai/member/dto/in/SocialMemberUpdateRequestDto.java, src/main/java/com/example/shinsekai/member/dto/out/KakaoTokenResponse.java, src/main/java/com/example/shinsekai/member/dto/out/KakaoUserResponse.java, src/main/java/com/example/shinsekai/member/dto/out/SignInResponseDto.java, src/main/java/com/example/shinsekai/member/entity/Member.java, src/main/java/com/example/shinsekai/member/infrastructure/MemberRepository.java, src/main/java/com/example/shinsekai/member/presentation/KakaoAuthController.java, src/main/java/com/example/shinsekai/member/vo/in/SocialMemberUpdateRequestVo.java
- Resolved #116 
- 소셜 로그인 환경 설정
- 카카오 로그인 개발
- 일반 회원을 카카오 회원으로 전환
=> Feat: 카카오 로그인 개발

src/main/java/com/example/shinsekai/address/application/AddressService.java, src/main/java/com/example/shinsekai/address/application/AddressServiceImpl.java, src/main/java/com/example/shinsekai/address/dto/in/AddressUpdateRequestDto.java, src/main/java/com/example/shinsekai/address/infrastructure/AddressRepository.java, src/main/java/com/example/shinsekai/address/presentation/AddressController.java, src/main/java/com/example/shinsekai/address/vo/AddressCreateRequestVo.java, src/main/java/com/example/shinsekai/address/vo/AddressUpdateRequestVo.java, src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java
- Resolved #118 
- 이름 중간에 띄어쓰기 있어도 되도록 허용
- 업데이트 로직 수정
- 기본배송지 조회 api추가
=> Fix: 배송지 오류 수정 및 기본배송지 조회API추가

src/main/java/com/example/shinsekai/card/application/StarbucksCardService.java, src/main/java/com/example/shinsekai/card/application/StarbucksCardServiceImpl.java, src/main/java/com/example/shinsekai/card/presentation/StarbucksCardController.java
- Resolves #122 
- 스타벅스 카드 단일 조회 api 추가
- 컨트롤러 HttpServletRequest 제거 후 memberUuid 가져오는 메서드로 변경
- 스타벅스 카드 삭제 시 잔액 검사(2차검사)
=> Feat : 스타벅스 카드 단일 조회 api

src/main/java/com/example/shinsekai/address/application/AddressServiceImpl.java, src/main/java/com/example/shinsekai/address/entity/Address.java, src/main/java/com/example/shinsekai/address/infrastructure/AddressRepository.java, src/main/java/com/example/shinsekai/address/vo/in/AddressCreateRequestVo.java, src/main/java/com/example/shinsekai/address/vo/in/AddressUpdateRequestVo.java
- #132 
- 저장된 데이터 세는 로직 수정(@query 어노테이션 사용)
- 배송 메모 null허용
=> Fix: 배송지 저장 로직 수정(저장된 데이터 데이터 개수 세는 로직 수정)

src/main/java/com/example/shinsekai/common/config/WebConfig.java, src/main/java/com/example/shinsekai/product/presentation/ProductController.java, src/main/java/com/example/shinsekai/util/OneBasedPageable.java, src/main/java/com/example/shinsekai/util/OneBasedPageableResolver.java
#36 
- OneBasedPageable 커스텀 어노테이션 생성
- 페이지 0이 아닌 1이 초기값
=> Feat: OneBasedPageable 커스텀 어노테이션

src/main/java/com/example/shinsekai/category/presentation/FilterController.java
- Resolves #40
- mainCategoryId가 없을 때, 전체 선택으로 간주
=> Fix: mainCategoryId가 없을 때, filter값 조회

src/main/java/com/example/shinsekai/address/application/AddressServiceImpl.java, src/main/java/com/example/shinsekai/address/dto/in/AddressUpdateRequestDto.java
- Resolved 141
- 배송지 업데이트 로직 수정
=> Feat: 저장된 기본배송지가 없는 상황에도 배송지가 업데이트되도록 수정

src/main/java/com/example/shinsekai/product/dto/out/ProductOutlineResponseDto.java, src/main/java/com/example/shinsekai/product/vo/out/ProductOutlineResponseVo.java
- 이 PR이 해결하는 문제나 기능을 연결한 이슈 번호를 작성합니다.  
예: `Closes #123` 또는 `Resolves #456`
- 이 PR에서 변경된 내용에 대해 간략히 설명합니다.  
예: 
- Spring Boot 기본 설정 추가
- `application.properties` 파일 초기 설정
- 기본 REST API 엔드포인트 생성
=> Fix : IsNew -> new 필드명 변경

src/main/java/com/example/shinsekai/season/dto/out/SeasonGetResponseDto.java, src/main/java/com/example/shinsekai/season/vo/out/SeasonGetResponseVo.java
=> Fix: Season전체 조회 응답 값 변경

src/main/java/com/example/shinsekai/event/dto/out/EventGetTitleResponseDto.java, src/main/java/com/example/shinsekai/event/vo/out/EventGetTitleResponseVo.java, src/main/java/com/example/shinsekai/option/dto/out/ColorResponseDto.java, src/main/java/com/example/shinsekai/option/dto/out/SizeResponseDto.java, src/main/java/com/example/shinsekai/option/presentation/ColorController.java, src/main/java/com/example/shinsekai/option/presentation/SizeController.java, src/main/java/com/example/shinsekai/option/vo/out/ColorResponseVo.java, src/main/java/com/example/shinsekai/option/vo/out/SizeResponseVo.java, src/main/java/com/example/shinsekai/season/dto/out/SeasonGetResponseDto.java, src/main/java/com/example/shinsekai/season/vo/out/SeasonGetResponseVo.java
- Resolves #24 
- Resolves #43
- Resolves #25
- id -> code
- `테이블`Name -> name
=> Fix: Season, Event, Color, Size 조회 응답 통일

src/main/java/com/example/shinsekai/address/entity/Address.java, src/main/java/com/example/shinsekai/address/vo/in/AddressCreateRequestVo.java, src/main/java/com/example/shinsekai/address/vo/in/AddressUpdateRequestVo.java
=> Feat: 배송지 컬럼 최대값 수정및 통일

src/main/java/com/example/shinsekai/member/presentation/KakaoAuthController.java
=> Feat: 소셜로그인 개발

src/main/java/com/example/shinsekai/address/application/AddressServiceImpl.java, src/main/java/com/example/shinsekai/address/infrastructure/AddressRepository.java, src/main/java/com/example/shinsekai/member/application/KakaoAuthServiceImpl.java, src/main/java/com/example/shinsekai/member/application/MemberServiceImpl.java, src/main/java/com/example/shinsekai/member/entity/Member.java
- Resolved  #157
- 닉네임 중복 체크 제거
- 메서드 이름 변경
=> Fix: 회원 관련 코드 수정

src/main/java/com/example/shinsekai/common/config/SecurityConfig.java
- #14
- 장바구니, 스타벅스 카드, 결제 API 인증시 사용 가능으로 변경
=> Feat: 특정 API 인증시 사용 가능으로 변경

src/main/java/com/example/shinsekai/purchase/application/OrderServiceImpl.java
- Closed #161 
- 주문 취소 시 환불 메서드 변경(use->charge)
=> Fix: 주문 취소시 환불 오류 수정

src/main/java/com/example/shinsekai/cart/application/CartService.java, src/main/java/com/example/shinsekai/cart/application/CartServiceImpl.java, src/main/java/com/example/shinsekai/cart/dto/out/CartGetDetailResponseDto.java, src/main/java/com/example/shinsekai/cart/dto/out/CartGetUuidResponseDto.java, src/main/java/com/example/shinsekai/cart/dto/out/CartGroupedByProductTypeDto.java, src/main/java/com/example/shinsekai/cart/dto/out/CartUuidGroupedByProductTypeDto.java, src/main/java/com/example/shinsekai/cart/infrastructure/CartRepository.java, src/main/java/com/example/shinsekai/cart/presentation/CartController.java, src/main/java/com/example/shinsekai/cart/vo/out/CartGetDetailResponseVo.java, src/main/java/com/example/shinsekai/cart/vo/out/CartGetUuidResponseVo.java, src/main/java/com/example/shinsekai/cart/vo/out/CartUuidGroupedByProductTypeVo.java
- #22
- 단순 UUID 조회용 API 추가
- 상세 정보 조회 API 추가
=> Feat: 장바구니 UUID 조회 API 및 상세 조회 API 분리

src/main/java/com/example/shinsekai/cart/application/CartService.java, src/main/java/com/example/shinsekai/cart/application/CartServiceImpl.java, src/main/java/com/example/shinsekai/cart/presentation/CartController.java
=> Fix: 장바구니 상세 조회 응답 수정

src/main/java/com/example/shinsekai/batch/common/BatchScheduler.java, src/main/java/com/example/shinsekai/batch/common/CronEntity.java, src/main/java/com/example/shinsekai/batch/common/CronRepository.java, src/main/java/com/example/shinsekai/batch/common/CronService.java, src/main/java/com/example/shinsekai/batch/common/DynamicBatchScheduler.java
- Resolves #174 
-  DB 기반 동적 크론으로 변경
- 배치 스케줄러 파일 이동 및 스케줄러 주석처리
=> Feat : 실서버 배치 테스트용

src/main/java/com/example/shinsekai/member/application/MemberServiceImpl.java, src/main/java/com/example/shinsekai/member/dto/in/SignUpRequestDto.java, src/main/java/com/example/shinsekai/member/vo/in/SignUpRequestVo.java
=> Fix: 약관 관련 로직 제거

src/main/java/com/example/shinsekai/purchase/application/PurchaseService.java, src/main/java/com/example/shinsekai/purchase/application/PurchaseServiceImpl.java, src/main/java/com/example/shinsekai/purchase/dto/out/PurchaseStatusResponseDto.java, src/main/java/com/example/shinsekai/purchase/entity/Purchase.java, src/main/java/com/example/shinsekai/purchase/entity/PurchaseStatus.java, src/main/java/com/example/shinsekai/purchase/infrastructure/PurchaseRepository.java, src/main/java/com/example/shinsekai/purchase/presentation/PurchaseController.java, src/main/java/com/example/shinsekai/purchase/vo/out/PurchaseStatusResponseVo.java
- Resolves #179 
- 주문 상태 ENUM 추가 및 변경
- 회원별 주문/배송현황 조회 API 생성
- 
=> Feat: 회원별 주문/배송현황 조회

src/main/java/com/example/shinsekai/common/entity/BaseResponseStatus.java, src/main/java/com/example/shinsekai/email/application/EmailServiceImpl.java, src/main/java/com/example/shinsekai/email/templete/RestockEmailBuilder.java, src/main/java/com/example/shinsekai/notification/application/RestockNotificationServiceImpl.java, src/main/java/com/example/shinsekai/notification/entity/RestockNotification.java, src/main/java/com/example/shinsekai/notification/infrastructure/RestockNotificationRepository.java, src/main/java/com/example/shinsekai/product/entity/Product.java, src/main/java/com/example/shinsekai/sse/application/SseService.java, src/main/java/com/example/shinsekai/sse/presentation/SseController.java
- Resolved  #181 
- SSE 연결 로직 개발
- 재입고 알림 메일 발송 시 SSE로 재입고 알림 보내는 로직 개발 
- 재입고 알림 테이블에 데이터는 존재하지만 SSE로 알림 받지 못한 사용자가 서버에 접속했을 때 알림 받을 수 있도록 로직 개발
=> Feat: SSE 개발

src/main/java/com/example/shinsekai/sse/presentation/SseController.java
=> Fix: SSE 수정

src/main/java/com/example/shinsekai/common/config/SecurityConfig.java, src/main/java/com/example/shinsekai/member/presentation/KakaoAuthController.java, src/main/java/com/example/shinsekai/member/vo/out/KakaoAuthUrlVo.java
-  #187
- 소셜 로그인 로직 수정: 카카오 로그인 url 응답함
=> Feat: 소셜 로그인 로직 수정

src/main/java/com/example/shinsekai/member/application/KakaoAuthService.java, src/main/java/com/example/shinsekai/member/application/KakaoAuthServiceImpl.java, src/main/java/com/example/shinsekai/member/presentation/KakaoAuthController.java
=> Feat: 소셜 로그인 응답 방식 수정

src/main/java/com/example/shinsekai/batch/PurchaseDailyAggregation/application/PurchaseDailyAggregationConfig.java, src/main/java/com/example/shinsekai/batch/PurchaseWeeklyAggregation/application/PurchaseWeeklyAggregationConfig.java, src/main/java/com/example/shinsekai/batch/bestProduct/application/BestProductConfig.java, src/main/java/com/example/shinsekai/batch/bestProduct/application/BestProductStepConfig.java, src/main/java/com/example/shinsekai/batch/bestProduct/application/ProductScoreStepConfig.java
- Resolve #193 
-cursor 기반으로 변경
-베스트 상품 테이블 생성 전 이전 데이터 삭제
-청크 사이즈 변경(성능 테스트 결과)
=> Fix : 집계 성능 개선 및 정책 변경

src/main/java/com/example/shinsekai/batch/deleteCart/application/DeleteCartConfig.java, src/main/java/com/example/shinsekai/category/application/MainCategoryServiceImpl.java, src/main/java/com/example/shinsekai/category/dto/in/MainCategoryUpdateRequestDto.java, src/main/java/com/example/shinsekai/category/dto/in/SubCategoryUpdateRequestDto.java, src/main/java/com/example/shinsekai/category/presentation/MainCategoryController.java, src/main/java/com/example/shinsekai/category/presentation/SubCategoryController.java, src/main/java/com/example/shinsekai/category/vo/in/MainCategoryUpdateRequestVo.java, src/main/java/com/example/shinsekai/category/vo/in/SubCategoryUpdateRequestVo.java
- #9 
- #23 
- 요청 데이터 전달 path+body → body 로 통일
- 배치 chunk 사이즈 최적값 500으로 변경
=> Refactor: Category 관련 코드 개선

src/main/java/com/example/shinsekai/notification/application/RestockNotificationService.java, src/main/java/com/example/shinsekai/notification/application/RestockNotificationServiceImpl.java, src/main/java/com/example/shinsekai/notification/dto/in/RestockNotificationRequestDto.java, src/main/java/com/example/shinsekai/notification/dto/out/RestockNotificationResponseDto.java, src/main/java/com/example/shinsekai/notification/entity/RestockNotification.java, src/main/java/com/example/shinsekai/notification/infrastructure/RestockNotificationRepository.java, src/main/java/com/example/shinsekai/notification/presentation/RestockNotificationController.java, src/main/java/com/example/shinsekai/notification/vo/out/RestockNotificationResponseVo.java
=> Fix: 재입고 알림 저장 로직 수정

src/main/java/com/example/shinsekai/batch/common/DynamicBatchScheduler.java
=> Fix : DB 크론 수정

src/main/java/com/example/shinsekai/address/application/AddressServiceImpl.java, src/main/java/com/example/shinsekai/address/infrastructure/AddressRepository.java, src/main/java/com/example/shinsekai/agreement/application/AgreementServiceImpl.java, src/main/java/com/example/shinsekai/agreement/infrastructure/MemberAgreementListRepository.java, src/main/java/com/example/shinsekai/email/application/EmailServiceImpl.java, src/main/java/com/example/shinsekai/member/application/KakaoAuthServiceImpl.java, src/main/java/com/example/shinsekai/member/application/MemberServiceImpl.java, src/main/java/com/example/shinsekai/member/presentation/KakaoAuthController.java, src/main/java/com/example/shinsekai/notification/application/RestockNotificationServiceImpl.java, src/main/java/com/example/shinsekai/notification/infrastructure/RestockNotificationRepository.java, src/main/java/com/example/shinsekai/sse/application/SseService.java
- #198
- 불필요 코드 제거
- 리팩토링
- sse 연결 5분으로 수정
=> Fix: 불필요 코드 제거 및 리팩토링

src/main/java/com/example/shinsekai/member/presentation/KakaoAuthController.java, src/main/java/com/example/shinsekai/notification/application/RestockNotificationService.java, src/main/java/com/example/shinsekai/notification/application/RestockNotificationServiceImpl.java, src/main/java/com/example/shinsekai/notification/infrastructure/RestockNotificationRepository.java, src/main/java/com/example/shinsekai/notification/presentation/RestockNotificationController.java, src/main/java/com/example/shinsekai/sse/application/SseService.java
- #202
- 회원별 재입고 알림 api 추가
- sse return 데이터 수정
=> Fix: 재입고 알림 로직 수정

src/main/java/com/example/shinsekai/notification/application/RestockNotificationServiceImpl.java, src/main/java/com/example/shinsekai/notification/infrastructure/RestockNotificationRepository.java, src/main/java/com/example/shinsekai/notification/presentation/RestockNotificationController.java, src/main/java/com/example/shinsekai/sse/application/SseService.java
-  #202
- 회원별 재입고 알림 api 추가
- sse return 데이터 수정
=> Fix: 카카오 로그인 수정

src/main/java/com/example/shinsekai/product/application/ProductJsonUploadService.java, src/main/java/com/example/shinsekai/product/presentation/ProductJsonUploadController.java
=> Feat : Json 샘플 상품 일분 업로드 API

src/main/java/com/example/shinsekai/purchase/dto/out/PurchaseResponseDto.java, src/main/java/com/example/shinsekai/purchase/vo/out/PurchaseResponseVo.java
-  Resolves #209
- DTO, VO 시간 추가
=> Fix : 주문내역조회 주문시간 추가

src/main/java/com/example/shinsekai/notification/application/RestockNotificationServiceImpl.java, src/main/java/com/example/shinsekai/notification/infrastructure/RestockNotificationRepository.java, src/main/java/com/example/shinsekai/sse/application/SseService.java
-  #211
- SSE 보내진 후 DB 업데이트하도록 수정
=> Fix: SSE 보내진 후 DB 업데이트하도록 수정

src/main/java/com/example/shinsekai/member/presentation/KakaoAuthController.java
=> Fix: 카카오 로그인 baseUrl 환경변수 처리
